
#ifndef ARBITO_CONFIG_H
#define ARBITO_CONFIG_H

#define MESSENGER_BUFFER_SIZE 1024
#define ORDER_DELAY_SEC 60
#define RECONNECT_DELAY_SEC 20
#define MAX_OPEN_ORDERS 1
#define MD_DELAY_MS 20

#endif //ARBITO_CONFIG_H
