
#ifndef ARBITO_CONFIG_H
#define ARBITO_CONFIG_H

#define MESSENGER_BUFFER_SIZE 1024
#define ORDER_DELAY_SEC 60
#define RECONNECT_DELAY_SEC 120
#define MAX_OPEN_ORDERS 5
#define MD_DELAY_US 10000

#endif //ARBITO_CONFIG_H
