//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2018-05-22 03:44:16 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-18 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>

#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793600L
#error LMAX_FIXM_traits.cpp version 1.4.0 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// LMAX_FIXM_traits.cpp
//-------------------------------------------------------------------------------------------------
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <cerrno>
#include <string.h>
// f8 includes
#include <fix8/f8exception.hpp>
#include <fix8/hypersleep.hpp>
#include <fix8/mpmc.hpp>
#include <fix8/thread.hpp>
#include <fix8/f8types.hpp>
#include <fix8/f8utils.hpp>
#include <fix8/tickval.hpp>
#include <fix8/logger.hpp>
#include <fix8/traits.hpp>
#include <fix8/field.hpp>
#include <fix8/message.hpp>
#include "fix8/LMAX_FIXM_types.hpp"
#include "fix8/LMAX_FIXM_router.hpp"
#include "fix8/LMAX_FIXM_classes.hpp"
//-------------------------------------------------------------------------------------------------
namespace FIX8 {
    namespace LMAX_FIXM {

//-------------------------------------------------------------------------------------------------
// Common group traits
        namespace {
        } // namespace

//-------------------------------------------------------------------------------------------------
// Message traits
//-------------------------------------------------------------------------------------------------
        const FieldTrait Heartbeat::_traits[]
                {
                        {112, 15, 1, 0, 0x04}
                };
        const FieldTrait_Hash_Array Heartbeat::_ftha(Heartbeat::_traits, Heartbeat::_fieldcnt);
        const MsgType Heartbeat::_msgtype("0");
//-------------------------------------------------------------------------------------------------
        const FieldTrait TestRequest::_traits[]
                {
                        {112, 15, 1, 0, 0x05}
                };
        const FieldTrait_Hash_Array TestRequest::_ftha(TestRequest::_traits, TestRequest::_fieldcnt);
        const MsgType TestRequest::_msgtype("1");
//-------------------------------------------------------------------------------------------------
        const FieldTrait ResendRequest::_traits[]
                {
                        {7,  4, 1, 0, 0x05},
                        {16, 4, 2, 0, 0x05}
                };
        const FieldTrait_Hash_Array ResendRequest::_ftha(ResendRequest::_traits, ResendRequest::_fieldcnt);
        const MsgType ResendRequest::_msgtype("2");
//-------------------------------------------------------------------------------------------------
        const FieldTrait Reject::_traits[]
                {
                        {45,  4,  1, 0, 0x05},
                        {58,  15, 5, 0, 0x04},
                        {371, 1,  2, 0, 0x04},
                        {372, 15, 3, 0, 0x04},
                        {373, 1,  4, 0, 0x04}
                };
        const FieldTrait_Hash_Array Reject::_ftha(Reject::_traits, Reject::_fieldcnt);
        const MsgType Reject::_msgtype("3");
//-------------------------------------------------------------------------------------------------
        const FieldTrait SequenceReset::_traits[]
                {
                        {36,  4, 2, 0, 0x05},
                        {123, 8, 1, 0, 0x04}
                };
        const FieldTrait_Hash_Array SequenceReset::_ftha(SequenceReset::_traits, SequenceReset::_fieldcnt);
        const MsgType SequenceReset::_msgtype("4");
//-------------------------------------------------------------------------------------------------
        const FieldTrait Logout::_traits[]
                {
                        {58, 15, 1, 0, 0x04}
                };
        const FieldTrait_Hash_Array Logout::_ftha(Logout::_traits, Logout::_fieldcnt);
        const MsgType Logout::_msgtype("5");
//-------------------------------------------------------------------------------------------------
        const FieldTrait Logon::_traits[]
                {
                        {98,  1,  1, 0, 0x05},
                        {108, 1,  2, 0, 0x05},
                        {141, 8,  3, 0, 0x04},
                        {383, 2,  4, 0, 0x04},
                        {553, 15, 5, 0, 0x04},
                        {554, 15, 6, 0, 0x04}
                };
        const FieldTrait_Hash_Array Logon::_ftha(Logon::_traits, Logon::_fieldcnt);
        const MsgType Logon::_msgtype("A");
//-------------------------------------------------------------------------------------------------
        const FieldTrait MarketDataRequest::_traits[]
                {
                        {146, 1,  6, 1, 0x1d},
                        {262, 15, 1, 0, 0x05},
                        {263, 7,  2, 0, 0x05},
                        {264, 1,  3, 0, 0x05},
                        {265, 1,  4, 0, 0x04},
                        {267, 1,  5, 4, 0x1d}
                };
        const FieldTrait_Hash_Array MarketDataRequest::_ftha(MarketDataRequest::_traits, MarketDataRequest::_fieldcnt);
        const MsgType MarketDataRequest::_msgtype("V");
//-------------------------------------------------------------------------------------------------
        const FieldTrait MarketDataRequest::NoRelatedSym::_traits[]
                {
                        {22, 15, 2, 2, 0x15},
                        {48, 15, 1, 2, 0x15}
                };
        const FieldTrait_Hash_Array
                MarketDataRequest::NoRelatedSym::_ftha(MarketDataRequest::NoRelatedSym::_traits,
                                                       NoRelatedSym::_fieldcnt);
        const MsgType MarketDataRequest::NoRelatedSym::_msgtype("NoRelatedSym");
//-------------------------------------------------------------------------------------------------
        const FieldTrait MarketDataRequest::NoMDEntryTypes::_traits[]
                {
                        {269, 7, 1, 0, 0x05}
                };
        const FieldTrait_Hash_Array
                MarketDataRequest::NoMDEntryTypes::_ftha(MarketDataRequest::NoMDEntryTypes::_traits,
                                                         NoMDEntryTypes::_fieldcnt);
        const MsgType MarketDataRequest::NoMDEntryTypes::_msgtype("NoMDEntryTypes");
//-------------------------------------------------------------------------------------------------
        const FieldTrait MarketDataSnapshotFullRefresh::_traits[]
                {
                        {22,  15, 3, 2, 0x15},
                        {48,  15, 2, 2, 0x15},
                        {262, 15, 1, 0, 0x04},
                        {268, 1,  4, 3, 0x1d}
                };
        const FieldTrait_Hash_Array MarketDataSnapshotFullRefresh::_ftha(MarketDataSnapshotFullRefresh::_traits,
                                                                         MarketDataSnapshotFullRefresh::_fieldcnt);
        const MsgType MarketDataSnapshotFullRefresh::_msgtype("W");
//-------------------------------------------------------------------------------------------------
        const FieldTrait MarketDataSnapshotFullRefresh::NoMDEntries::_traits[]
                {
                        {269, 7,  1, 0, 0x05},
                        {270, 11, 2, 0, 0x04},
                        {271, 10, 3, 0, 0x04},
                        {272, 24, 4, 0, 0x04},
                        {273, 23, 5, 0, 0x04}
                };
        const FieldTrait_Hash_Array
                MarketDataSnapshotFullRefresh::NoMDEntries::_ftha(MarketDataSnapshotFullRefresh::NoMDEntries::_traits,
                                                                  NoMDEntries::_fieldcnt);
        const MsgType MarketDataSnapshotFullRefresh::NoMDEntries::_msgtype("NoMDEntries");
//-------------------------------------------------------------------------------------------------
        const FieldTrait MarketDataRequestReject::_traits[]
                {
                        {58,  15, 3, 0, 0x04},
                        {262, 15, 1, 0, 0x05},
                        {281, 7,  2, 0, 0x04}
                };
        const FieldTrait_Hash_Array MarketDataRequestReject::_ftha(MarketDataRequestReject::_traits,
                                                                   MarketDataRequestReject::_fieldcnt);
        const MsgType MarketDataRequestReject::_msgtype("Y");
//-------------------------------------------------------------------------------------------------
        const FieldTrait header::_traits[]
                {
                        {8,   15, 1,  0, 0x64},
                        {9,   2,  2,  0, 0x64},
                        {34,  4,  6,  0, 0x05},
                        {35,  15, 3,  0, 0x44},
                        {43,  8,  7,  0, 0x04},
                        {49,  15, 4,  0, 0x05},
                        {52,  22, 9,  0, 0x05},
                        {56,  15, 5,  0, 0x05},
                        {97,  8,  8,  0, 0x04},
                        {122, 22, 10, 0, 0x04}
                };
        const FieldTrait_Hash_Array header::_ftha(header::_traits, header::_fieldcnt);
        const MsgType header::_msgtype("header");
//-------------------------------------------------------------------------------------------------
        const FieldTrait trailer::_traits[]
                {
                        {10, 15, 1, 0, 0x64}
                };
        const FieldTrait_Hash_Array trailer::_ftha(trailer::_traits, trailer::_fieldcnt);
        const MsgType trailer::_msgtype("trailer");

    } // namespace LMAX_FIXM
} // namespace FIX8
